### ISSUE TITLE
open file with extension from menu

### ISSUE THREAD

**Issue by tyzmodo** [martinrotter/textosaurus#83] opened 2020-04-15 02:22 UTC
#### Brief description of the issue.

the file extension recognizer in menu-->file-->open doesn't work,you have to drap&drop or rely on sidebar file browser

#### How to reproduce the bug?

1. from menu click file-->open file
2. choose a file name extension like '*.txt'or "*.c"
3. no file displayed,only folders listed

#### What is the expected result?

the file with selected extension name should be displayed

#### What actually happened?
no file displayed,only folders listed

**Comment by martinrotter** [comment] 2020-04-15 05:00
which OS do you use? do you use latest textosaurus version? does latest dev build - https://github.com/martinrotter/textosaurus/wiki/Development-builds work?

can you perhaps make a short screen-cast video to demonstrate the bug?

**Comment by tyzmodo** [comment] 2020-04-15 06:19
I tried the latest dev build appimages of winodws and linux at home,the problem appears.
the dev build link seems expired now so here at my workspace I use a previous downloaded eb848e0 commit appimage to record the video . the video is zipped to attach.
[screenrecord.zip](https://github.com/martinrotter/textosaurus/files/4479416/screenrecord.zip)

**Comment by tyzmodo** [comment] 2020-04-15 06:21
sorry i forgot to mention ,my windows version is windows7 x64 my linux version is archlinux,here my linux os at work is linux lite which is similiar to ubuntu. both os is of zh_cn locale

**Comment by martinrotter** [comment] 2020-04-15 06:26
i see, i cannot reproduce problem, it just works here, i will do some checks

**Comment by martinrotter** [comment] 2020-04-15 08:22
I committed [new changes](https://github.com/martinrotter/textosaurus/commit/1717d27b15c2b9cc472ae785ce0ec9ef9168455c), I added launch flag `--nativedialogs` which, if used, forces usage of native dialogs which might work better than Qt dialogs for some users.

So wait until new dev build gets generated and then launch Textosaurus with `textosaurus.exe --nativedialogs` and try to simulate bug and see if it is resolved with this switch ON.

**Comment by tyzmodo** [comment] 2020-04-15 09:23
Ok,thank you

**Comment by tyzmodo** [comment] 2020-04-15 10:03
Yes,the problem is solved by setting that option on,thank you very much!

**Closed** 2020-04-15 10:03 UTC
Labels: Component-GUI, Type-Bug
